### ISSUE TITLE
Can you add an option for CSV as well,  also can you make it more optimised version of this.

### ISSUE THREAD

**Issue by yoosuf** [samithaHewawasam/laravel-redis-queue#2]
https://github.com/samithaHewawasam/laravel-redis-queue/blob/8238b18e80f75e0bafeea2e6e99623cfc92195fe/app/Http/Controllers/DataController.php#L29

**Comment by samithaHewawasam** [comment]
CSV and EXCEL both work inside that function. that's why i kept it there
